export const INPUT_FOCUS = 'header/input_focus'
export const INPUT_BLUR = 'header/input_blur'
export const GET_LIST_ITEM = 'header/get_list_item'
export const MOUSE_ENTER = 'header/mouse_enter'
export const MOUSE_LEAVE = 'header/mouse_leave'
export const SWITCH_PAGE = 'header/switch_page'
